import { 
  RouteSegment, 
  Shipment, 
  Vehicle, 
  Incident, 
  EvidenceItem, 
  AlertItem, 
  AuditEvent 
} from '../types';

export const INITIAL_ROUTES: RouteSegment[] = [
  {
    id: 'ROUTE-NH-10',
    code: 'NH-10',
    name: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    origin: 'Siliguri Terminal [WB]',
    destination: 'Gangtok STNM Hospital [SK]',
    originCoord: { lat: 26.7271, lng: 88.3953 },
    destCoord: { lat: 27.3389, lng: 88.6065 },
    distanceKm: 114,
    stdEtaMinutes: 210, // 3h 30m
    currentEtaMinutes: 210,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 28,
    confidence: 94,
    accessibility: 'OPEN',
    elevationMsl: '1,650 m to 2,120 m',
    sector: 'Sector 02-NER (Sikkim Artery)',
    precipitationMmHr: 42,
    soilSaturationPct: 76,
    activeIncidentsCount: 0,
    evidenceCount: 2,
    lastUpdated: '11:42 IST',
    description: 'Primary lifeline arterial highway connecting plains of North Bengal with Sikkim. Mountain corridor hugging Teesta river valley prone to monsoon landslides.',
    waypoints: [
      { lat: 26.7271, lng: 88.3953 }, // Siliguri
      { lat: 26.8845, lng: 88.4735 }, // Sevoke Coronation Bridge
      { lat: 26.9854, lng: 88.4891 }, // 29th Mile / Teesta Bazaar
      { lat: 27.1724, lng: 88.5284 }, // Rangpo Checkpost
      { lat: 27.2401, lng: 88.5822 }, // Singtam
      { lat: 27.3389, lng: 88.6065 }, // Gangtok
    ],
    alternativeRouteIds: ['ROUTE-ALT-B'],
    isAlternative: false,
  },
  {
    id: 'ROUTE-ALT-B',
    code: 'ALT-B',
    name: 'Corridor Alt-B (Via Lava - Algarah - Reshi - Rhenock)',
    origin: 'Siliguri / Sevoke Bypass [WB]',
    destination: 'Gangtok STNM Hospital [SK]',
    originCoord: { lat: 26.8845, lng: 88.4735 },
    destCoord: { lat: 27.3389, lng: 88.6065 },
    distanceKm: 142,
    stdEtaMinutes: 285, // 4h 45m
    currentEtaMinutes: 285,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 24,
    confidence: 97,
    accessibility: 'OPEN',
    elevationMsl: '1,820 m to 2,350 m',
    sector: 'Sector 02-NER Ridge Contingency',
    precipitationMmHr: 18,
    soilSaturationPct: 52,
    activeIncidentsCount: 0,
    evidenceCount: 1,
    lastUpdated: '11:40 IST',
    description: 'All-weather elevated ridge route bypassing low-lying Teesta canyon. Cleared for multi-axle freight up to 28 Metric Tonnes with 24/7 BRO bulldozer detachment at Algarah.',
    waypoints: [
      { lat: 26.8845, lng: 88.4735 }, // Sevoke
      { lat: 27.0542, lng: 88.5912 }, // Kalimpong
      { lat: 27.0865, lng: 88.6611 }, // Lava
      { lat: 27.1245, lng: 88.6322 }, // Algarah
      { lat: 27.1652, lng: 88.6189 }, // Reshi border
      { lat: 27.2185, lng: 88.6277 }, // Rhenock
      { lat: 27.2841, lng: 88.6190 }, // Pakyong
      { lat: 27.3389, lng: 88.6065 }, // Gangtok
    ],
    isAlternative: true,
  },
  {
    id: 'ROUTE-NH-27',
    code: 'NH-27',
    name: 'NH-27 (Guwahati HQ - Nagaon - Tezpur)',
    origin: 'Guwahati Central Depot [AS]',
    destination: 'Tezpur Base Terminal [AS]',
    originCoord: { lat: 26.1445, lng: 91.7362 },
    destCoord: { lat: 26.6528, lng: 92.7926 },
    distanceKm: 182,
    stdEtaMinutes: 210,
    currentEtaMinutes: 210,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 14,
    confidence: 96,
    accessibility: 'OPEN',
    elevationMsl: '55 m to 90 m',
    sector: 'Sector 01-NER Brahmaputra Plains',
    precipitationMmHr: 16,
    soilSaturationPct: 45,
    activeIncidentsCount: 0,
    evidenceCount: 1,
    lastUpdated: '11:44 IST',
    description: 'Four-lane East-West high speed logistics spine. Excellent pavement rating, monitored by automated FASTag CCTV toll gantries.',
    waypoints: [
      { lat: 26.1445, lng: 91.7362 }, // Guwahati
      { lat: 26.1950, lng: 92.1240 }, // Jagiroad
      { lat: 26.3470, lng: 92.6840 }, // Nagaon bypass
      { lat: 26.6528, lng: 92.7926 }, // Tezpur
    ],
  },
  {
    id: 'ROUTE-NH-6',
    code: 'NH-6',
    name: 'NH-6 (Shillong - Jowai - Silchar)',
    origin: 'Shillong Transport Hub [ML]',
    destination: 'Silchar Civil Depot [AS]',
    originCoord: { lat: 25.5788, lng: 91.8933 },
    destCoord: { lat: 24.8333, lng: 92.7789 },
    distanceKm: 215,
    stdEtaMinutes: 340,
    currentEtaMinutes: 385,
    delayMinutes: 45,
    status: 'DEGRADED',
    riskScore: 48,
    confidence: 92,
    accessibility: 'DEGRADED',
    elevationMsl: '350 m to 1,520 m',
    sector: 'Sector 03-NER Barak Valley Transit',
    precipitationMmHr: 64,
    soilSaturationPct: 82,
    activeIncidentsCount: 1,
    evidenceCount: 2,
    lastUpdated: '11:35 IST',
    description: 'Vital artery connecting Barak valley, Tripura, and Mizoram. High rainfall across Meghalaya plateau creates slippery surface sludge and wheel drag.',
    waypoints: [
      { lat: 25.5788, lng: 91.8933 }, // Shillong
      { lat: 25.4485, lng: 92.2033 }, // Jowai
      { lat: 25.1294, lng: 92.3845 }, // Ratacherra
      { lat: 24.8333, lng: 92.7789 }, // Silchar
    ],
  },
  {
    id: 'ROUTE-NH-29',
    code: 'NH-29',
    name: 'NH-29 (Dimapur - Kohima Bypass)',
    origin: 'Dimapur Freight Railhead [NL]',
    destination: 'Kohima Forward Depot [NL]',
    originCoord: { lat: 25.9044, lng: 93.7275 },
    destCoord: { lat: 25.6751, lng: 94.1086 },
    distanceKm: 74,
    stdEtaMinutes: 135,
    currentEtaMinutes: 180,
    delayMinutes: 45,
    status: 'HIGH-RISK',
    riskScore: 74,
    confidence: 90,
    accessibility: 'HIGH-RISK',
    elevationMsl: '260 m to 1,444 m',
    sector: 'Sector 04-NER Naga Hills',
    precipitationMmHr: 72,
    soilSaturationPct: 89,
    activeIncidentsCount: 1,
    evidenceCount: 1,
    lastUpdated: '11:32 IST',
    description: 'Challenging geologically active mountain highway with ongoing hillside subsidence near KM 64. Speed restricted to 25 km/h for heavy multi-axles.',
    waypoints: [
      { lat: 25.9044, lng: 93.7275 }, // Dimapur
      { lat: 25.7922, lng: 25.9120 }, // Chumukedima
      { lat: 25.7201, lng: 93.9984 }, // Medziphema
      { lat: 25.6751, lng: 94.1086 }, // Kohima
    ],
  },
  {
    id: 'ROUTE-NH-15',
    code: 'NH-15',
    name: 'NH-15 (Tezpur - North Lakhimpur - Pasighat)',
    origin: 'Tezpur Crossing [AS]',
    destination: 'Pasighat Depot [AR]',
    originCoord: { lat: 26.6528, lng: 92.7926 },
    destCoord: { lat: 28.0664, lng: 95.3262 },
    distanceKm: 275,
    stdEtaMinutes: 360,
    currentEtaMinutes: 360,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 22,
    confidence: 91,
    accessibility: 'OPEN',
    elevationMsl: '80 m to 155 m',
    sector: 'Sector 05-NER North Bank Corridor',
    precipitationMmHr: 22,
    soilSaturationPct: 54,
    activeIncidentsCount: 0,
    evidenceCount: 1,
    lastUpdated: '11:15 IST',
    description: 'Northern bank Brahmaputra alternative lifeline to eastern Arunachal foothills. Stable embankment.',
    waypoints: [
      { lat: 26.6528, lng: 92.7926 }, // Tezpur
      { lat: 27.2341, lng: 94.1042 }, // North Lakhimpur
      { lat: 28.0664, lng: 95.3262 }, // Pasighat
    ],
  },
  {
    id: 'ROUTE-NH-13',
    code: 'NH-13',
    name: 'NH-13 (Bhalukpong - Bomdila - Tawang)',
    origin: 'Bhalukpong Gate [AR]',
    destination: 'Tawang Civil Supplies [AR]',
    originCoord: { lat: 27.0118, lng: 92.6453 },
    destCoord: { lat: 27.5861, lng: 91.8687 },
    distanceKm: 232,
    stdEtaMinutes: 440,
    currentEtaMinutes: 490,
    delayMinutes: 50,
    status: 'HIGH-RISK',
    riskScore: 68,
    confidence: 88,
    accessibility: 'HIGH-RISK',
    elevationMsl: '213 m to 4,170 m (Sela Pass)',
    sector: 'Sector 06-NER Kameng High Altitude',
    precipitationMmHr: 58,
    soilSaturationPct: 78,
    activeIncidentsCount: 1,
    evidenceCount: 1,
    lastUpdated: '11:10 IST',
    description: 'High-altitude strategic frontier corridor traversing Sela Tunnel / Pass. Rapid weather shifts and intermittent boulder falls.',
    waypoints: [
      { lat: 27.0118, lng: 92.6453 }, // Bhalukpong
      { lat: 27.2644, lng: 92.4215 }, // Bomdila
      { lat: 27.5032, lng: 92.1022 }, // Sela
      { lat: 27.5861, lng: 91.8687 }, // Tawang
    ],
  },
  {
    id: 'ROUTE-NH-715',
    code: 'NH-715',
    name: 'NH-715 (Jorhat - Kaziranga - Kaliabor)',
    origin: 'Jorhat Hub [AS]',
    destination: 'Kaliabor Crossing [AS]',
    originCoord: { lat: 26.7509, lng: 94.2037 },
    destCoord: { lat: 26.5824, lng: 93.0038 },
    distanceKm: 128,
    stdEtaMinutes: 160,
    currentEtaMinutes: 195,
    delayMinutes: 35,
    status: 'DEGRADED',
    riskScore: 56,
    confidence: 93,
    accessibility: 'DEGRADED',
    elevationMsl: '70 m to 85 m',
    sector: 'Sector 01-NER Central Floodplain',
    precipitationMmHr: 48,
    soilSaturationPct: 88,
    activeIncidentsCount: 1,
    evidenceCount: 1,
    lastUpdated: '11:20 IST',
    description: 'Corridor bordering Kaziranga national park. Animal transit corridors and occasional river overflow during monsoon surge.',
    waypoints: [
      { lat: 26.7509, lng: 94.2037 }, // Jorhat
      { lat: 26.5772, lng: 93.1711 }, // Kaziranga
      { lat: 26.5824, lng: 93.0038 }, // Kaliabor
    ],
  },
  {
    id: 'ROUTE-NH-37',
    code: 'NH-37',
    name: 'NH-37 (Guwahati - Goalpara - Bongaigaon)',
    origin: 'Guwahati West [AS]',
    destination: 'Bongaigaon Refinery [AS]',
    originCoord: { lat: 26.1445, lng: 91.7362 },
    destCoord: { lat: 26.4833, lng: 90.5667 },
    distanceKm: 165,
    stdEtaMinutes: 190,
    currentEtaMinutes: 190,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 16,
    confidence: 95,
    accessibility: 'OPEN',
    elevationMsl: '45 m to 65 m',
    sector: 'Sector 01-NER Lower Assam',
    precipitationMmHr: 12,
    soilSaturationPct: 40,
    activeIncidentsCount: 0,
    evidenceCount: 0,
    lastUpdated: '11:25 IST',
    description: 'Major petrochemical and bulk transport artery in lower Assam. Fully operational.',
    waypoints: [
      { lat: 26.1445, lng: 91.7362 }, // Guwahati
      { lat: 26.1667, lng: 90.6167 }, // Goalpara
      { lat: 26.4833, lng: 90.5667 }, // Bongaigaon
    ],
  },
  {
    id: 'ROUTE-NH-208',
    code: 'NH-208',
    name: 'NH-208 (Silchar - Kumarghat - Agartala)',
    origin: 'Silchar Civil Depot [AS]',
    destination: 'Agartala Central Warehouse [TR]',
    originCoord: { lat: 24.8333, lng: 92.7789 },
    destCoord: { lat: 23.8315, lng: 91.2868 },
    distanceKm: 248,
    stdEtaMinutes: 380,
    currentEtaMinutes: 380,
    delayMinutes: 0,
    status: 'OPEN',
    riskScore: 32,
    confidence: 89,
    accessibility: 'OPEN',
    elevationMsl: '15 m to 240 m',
    sector: 'Sector 07-NER Tripura Inter-State',
    precipitationMmHr: 28,
    soilSaturationPct: 62,
    activeIncidentsCount: 0,
    evidenceCount: 0,
    lastUpdated: '10:55 IST',
    description: 'Interstate link into Tripura. Regular maintenance ongoing, clear of major obstructions.',
    waypoints: [
      { lat: 24.8333, lng: 92.7789 }, // Silchar
      { lat: 24.1611, lng: 92.0319 }, // Kumarghat
      { lat: 23.8315, lng: 91.2868 }, // Agartala
    ],
  },
];

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: 'MED-2045',
    commodity: 'Emergency Hemodialysis Units & Cryo Blood Plasma',
    priority: 'CRITICAL',
    origin: 'Guwahati Central Depot [AS]',
    destination: 'Gangtok STNM Hospital [SK]',
    driverName: 'Manabendra Kalita',
    driverPhone: '+91 94350 28190',
    vehicleId: 'TRK-AS-1029',
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    eta: '15:15 IST (Std)',
    status: 'IN TRANSIT',
    riskScore: 28,
    isCritical: true,
    cargoWeightTonnes: 4.8,
    lastUpdate: '11:42 IST',
    notes: 'Temperature-sensitive medical refrigeration units. Life-critical deployment for STNM dialysis ward.',
  },
  {
    id: 'OXY-902',
    commodity: 'Liquid Medical Oxygen (12T Cryogenic Tank)',
    priority: 'CRITICAL',
    origin: 'Bongaigaon Refinery [AS]',
    destination: 'Tezpur Base Hospital [AS]',
    driverName: 'Prabhat Baruah',
    driverPhone: '+91 98640 11928',
    vehicleId: 'TRK-AS-4011',
    routeId: 'ROUTE-NH-27',
    routeName: 'NH-27 (Guwahati - Nagaon - Tezpur)',
    eta: '14:50 IST',
    status: 'IN TRANSIT',
    riskScore: 14,
    isCritical: true,
    cargoWeightTonnes: 12.0,
    lastUpdate: '11:40 IST',
    notes: 'Dedicated hazardous cryogenic escort. Real-time pressure telemetry active.',
  },
  {
    id: 'MED-1108',
    commodity: 'Trauma Surgical Kits & Anti-Venom Serums',
    priority: 'CRITICAL',
    origin: 'Guwahati Central Depot [AS]',
    destination: 'Tawang Civil Supplies [AR]',
    driverName: 'Tenzing Norbu',
    driverPhone: '+91 94360 44810',
    vehicleId: 'TRK-AR-5120',
    routeId: 'ROUTE-NH-13',
    routeName: 'NH-13 (Bhalukpong - Bomdila - Tawang)',
    eta: '19:30 IST',
    status: 'IN TRANSIT',
    riskScore: 68,
    isCritical: true,
    cargoWeightTonnes: 3.2,
    lastUpdate: '11:38 IST',
    notes: 'High-altitude cold chain validated. Convoy accompanied by armed paramilitary escort.',
  },
  {
    id: 'RAT-3012',
    commodity: 'NDRF High-Energy Dry Rations & Potable Water Packs',
    priority: 'HIGH',
    origin: 'Shillong Transport Hub [ML]',
    destination: 'Silchar Civil Depot [AS]',
    driverName: 'Lalrintluanga Hmar',
    driverPhone: '+91 98620 33819',
    vehicleId: 'TRK-ML-0932',
    routeId: 'ROUTE-NH-6',
    routeName: 'NH-6 (Shillong - Jowai - Silchar)',
    eta: '17:45 IST',
    status: 'DELAYED',
    riskScore: 48,
    isCritical: false,
    cargoWeightTonnes: 18.0,
    lastUpdate: '11:30 IST',
    notes: 'Disaster response replenishment. Delayed due to clay mud sludge at Jowai pass.',
  },
  {
    id: 'DIS-9901',
    commodity: 'Modular Disaster Relief Shelter Frameworks',
    priority: 'HIGH',
    origin: 'Dimapur Freight Railhead [NL]',
    destination: 'Kohima Forward Depot [NL]',
    driverName: 'Imtitemjen Ao',
    driverPhone: '+91 94362 77014',
    vehicleId: 'TRK-NL-2201',
    routeId: 'ROUTE-NH-29',
    routeName: 'NH-29 (Dimapur - Kohima Bypass)',
    eta: '14:15 IST',
    status: 'IN TRANSIT',
    riskScore: 74,
    isCritical: false,
    cargoWeightTonnes: 14.5,
    lastUpdate: '11:32 IST',
    notes: 'Pre-fabricated shelter tents for emergency camps. Slowed due to shoulder fissure warning.',
  },
  {
    id: 'AGR-4420',
    commodity: 'High-Yield Rice Seed Stock & Organic Fertilizers',
    priority: 'NORMAL',
    origin: 'Jorhat Hub [AS]',
    destination: 'Kaliabor Agricultural Co-op [AS]',
    driverName: 'Bikram Saikia',
    driverPhone: '+91 94351 99201',
    vehicleId: 'TRK-AS-7733',
    routeId: 'ROUTE-NH-715',
    routeName: 'NH-715 (Jorhat - Kaziranga - Kaliabor)',
    eta: '15:40 IST',
    status: 'IN TRANSIT',
    riskScore: 56,
    isCritical: false,
    cargoWeightTonnes: 22.0,
    lastUpdate: '11:20 IST',
    notes: 'Kharif seasonal agricultural distribution.',
  },
  {
    id: 'CON-8840',
    commodity: 'Pre-Stressed Concrete Bridge Girders',
    priority: 'HIGH',
    origin: 'Bongaigaon Casting Yard [AS]',
    destination: 'Guwahati West Interchange [AS]',
    driverName: 'Dhrubajyoti Nath',
    driverPhone: '+91 98540 88219',
    vehicleId: 'TRK-AS-3310',
    routeId: 'ROUTE-NH-37',
    routeName: 'NH-37 (Guwahati - Goalpara - Bongaigaon)',
    eta: '16:00 IST',
    status: 'IN TRANSIT',
    riskScore: 16,
    isCritical: false,
    cargoWeightTonnes: 26.0,
    lastUpdate: '11:25 IST',
    notes: 'Heavy multi-axle oversized freight. Pilot escort vehicle leading.',
  },
  {
    id: 'MED-3391',
    commodity: 'Pediatric Vaccines & Maternal Healthcare Kits',
    priority: 'HIGH',
    origin: 'Silchar Civil Depot [AS]',
    destination: 'Agartala Central Warehouse [TR]',
    driverName: 'Subrata Debnath',
    driverPhone: '+91 94361 70293',
    vehicleId: 'TRK-MZ-3109',
    routeId: 'ROUTE-NH-208',
    routeName: 'NH-208 (Silchar - Kumarghat - Agartala)',
    eta: '18:10 IST',
    status: 'IN TRANSIT',
    riskScore: 32,
    isCritical: false,
    cargoWeightTonnes: 2.4,
    lastUpdate: '11:15 IST',
    notes: 'Routine public immunization supply.',
  },
  {
    id: 'WTR-5502',
    commodity: 'Community Mobile Water Filtration & Chlorination Plants',
    priority: 'HIGH',
    origin: 'Tezpur Crossing [AS]',
    destination: 'Pasighat Relief Camp [AR]',
    driverName: 'Pema Wangdi',
    driverPhone: '+91 94368 11094',
    vehicleId: 'TRK-SK-0844',
    routeId: 'ROUTE-NH-15',
    routeName: 'NH-15 (Tezpur - North Lakhimpur - Pasighat)',
    eta: '17:30 IST',
    status: 'IN TRANSIT',
    riskScore: 22,
    isCritical: false,
    cargoWeightTonnes: 8.5,
    lastUpdate: '11:18 IST',
    notes: 'Flood resilience clean drinking water deployment.',
  },
  {
    id: 'POL-6610',
    commodity: 'High-Altitude Diesel Fuel (Winter Grade Arctic Blend)',
    priority: 'NORMAL',
    origin: 'Siliguri Terminal [WB]',
    destination: 'Gangtok IOCL Depot [SK]',
    driverName: 'Rajen Pradhan',
    driverPhone: '+91 97330 45812',
    vehicleId: 'TRK-WB-9018',
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    eta: '16:45 IST',
    status: 'ASSIGNED',
    riskScore: 28,
    isCritical: false,
    cargoWeightTonnes: 20.0,
    lastUpdate: '10:50 IST',
    notes: 'Bulk petroleum convoy waiting dispatch clearance.',
  },
  {
    id: 'SUR-4022',
    commodity: 'ICU Ventilator Consumables & Surgical Infusions',
    priority: 'HIGH',
    origin: 'Siliguri Terminal [WB]',
    destination: 'Namchi District Hospital [SK]',
    driverName: 'Karma Bhutia',
    driverPhone: '+91 97341 88204',
    vehicleId: 'TRK-SK-2190',
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    eta: '16:15 IST',
    status: 'IN TRANSIT',
    riskScore: 28,
    isCritical: false,
    cargoWeightTonnes: 3.6,
    lastUpdate: '11:35 IST',
    notes: 'Secondary medical consignment en route to South Sikkim.',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'TRK-SK-2190',
    vehicleNumber: 'SK-02-B-2190 (Tata 1109)',
    driverName: 'Karma Bhutia',
    driverPhone: '+91 97341 88204',
    assignedShipmentId: 'SUR-4022',
    commodity: 'ICU Consumables & Infusions',
    lat: 26.8500,
    lng: 88.4500, // Near Sevoke
    speedKmh: 38,
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    eta: '4h 10m',
    riskLevel: 'LOW',
    lastGpsUpdate: 'Just now',
    status: 'MOVING',
    headingDeg: 35,
    currentWaypointIndex: 1,
  },
  {
    id: 'TRK-AS-1029',
    vehicleNumber: 'AS-01-EC-1029 (Tata Signa 2823)',
    driverName: 'Manabendra Kalita',
    driverPhone: '+91 94350 28190',
    assignedShipmentId: 'MED-2045',
    commodity: 'Emergency Hemodialysis Units',
    lat: 26.9400,
    lng: 88.4820, // Near Sevoke / approaching Mile 29
    speedKmh: 42,
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    eta: '3h 30m',
    riskLevel: 'LOW',
    lastGpsUpdate: 'Just now',
    status: 'MOVING',
    headingDeg: 38,
    currentWaypointIndex: 1,
  },
  {
    id: 'TRK-AS-4011',
    vehicleNumber: 'AS-01-GC-4011 (Ashok Leyland Ecomet Cryo)',
    driverName: 'Prabhat Baruah',
    driverPhone: '+91 98640 11928',
    assignedShipmentId: 'OXY-902',
    commodity: 'Liquid Medical Oxygen (12T)',
    lat: 26.4210,
    lng: 92.4100, // On NH-27 near Nagaon
    speedKmh: 68,
    routeId: 'ROUTE-NH-27',
    routeName: 'NH-27 (Guwahati - Nagaon - Tezpur)',
    eta: '2h 10m',
    riskLevel: 'LOW',
    lastGpsUpdate: '1 min ago',
    status: 'MOVING',
    headingDeg: 65,
    currentWaypointIndex: 2,
  },
  {
    id: 'TRK-ML-0932',
    vehicleNumber: 'ML-05-D-0932 (Eicher Pro 3019)',
    driverName: 'Lalrintluanga Hmar',
    driverPhone: '+91 98620 33819',
    assignedShipmentId: 'RAT-3012',
    commodity: 'NDRF Dry Rations & Water',
    lat: 25.3200,
    lng: 92.2900, // Near Jowai
    speedKmh: 24,
    routeId: 'ROUTE-NH-6',
    routeName: 'NH-6 (Shillong - Jowai - Silchar)',
    eta: '5h 15m',
    riskLevel: 'MEDIUM',
    lastGpsUpdate: '2 mins ago',
    status: 'MOVING',
    headingDeg: 145,
    currentWaypointIndex: 1,
  },
  {
    id: 'TRK-NL-2201',
    vehicleNumber: 'NL-07-A-2201 (BharatBenz 1617)',
    driverName: 'Imtitemjen Ao',
    driverPhone: '+91 94362 77014',
    assignedShipmentId: 'DIS-9901',
    commodity: 'Prefab Shelter Frameworks',
    lat: 25.7500,
    lng: 93.9200, // Climbing toward Kohima
    speedKmh: 31,
    routeId: 'ROUTE-NH-29',
    routeName: 'NH-29 (Dimapur - Kohima Bypass)',
    eta: '2h 45m',
    riskLevel: 'HIGH',
    lastGpsUpdate: '1 min ago',
    status: 'MOVING',
    headingDeg: 110,
    currentWaypointIndex: 2,
  },
  {
    id: 'TRK-AR-5120',
    vehicleNumber: 'AR-01-B-5120 (Mahindra Blazo X 4x4)',
    driverName: 'Tenzing Norbu',
    driverPhone: '+91 94360 44810',
    assignedShipmentId: 'MED-1108',
    commodity: 'Trauma Surgical Kits',
    lat: 27.3800,
    lng: 92.2500, // Near Bomdila
    speedKmh: 28,
    routeId: 'ROUTE-NH-13',
    routeName: 'NH-13 (Bhalukpong - Bomdila - Tawang)',
    eta: '6h 30m',
    riskLevel: 'HIGH',
    lastGpsUpdate: '3 mins ago',
    status: 'MOVING',
    headingDeg: 315,
    currentWaypointIndex: 2,
  },
  {
    id: 'TRK-SK-0844',
    vehicleNumber: 'SK-01-E-0844 (Tata Ultra T.16)',
    driverName: 'Pema Wangdi',
    driverPhone: '+91 94368 11094',
    assignedShipmentId: 'WTR-5502',
    commodity: 'Water Filtration Plants',
    lat: 27.5100,
    lng: 94.6200, // Approaching North Lakhimpur
    speedKmh: 54,
    routeId: 'ROUTE-NH-15',
    routeName: 'NH-15 (Tezpur - North Lakhimpur - Pasighat)',
    eta: '4h 20m',
    riskLevel: 'LOW',
    lastGpsUpdate: '2 mins ago',
    status: 'MOVING',
    headingDeg: 55,
    currentWaypointIndex: 1,
  },
  {
    id: 'TRK-AS-7733',
    vehicleNumber: 'AS-03-BC-7733 (Ashok Leyland 2820)',
    driverName: 'Bikram Saikia',
    driverPhone: '+91 94351 99201',
    assignedShipmentId: 'AGR-4420',
    commodity: 'Rice Seed Stock & Fertilizers',
    lat: 26.6200,
    lng: 93.4100, // Near Kaziranga
    speedKmh: 48,
    routeId: 'ROUTE-NH-715',
    routeName: 'NH-715 (Jorhat - Kaziranga - Kaliabor)',
    eta: '3h 10m',
    riskLevel: 'MEDIUM',
    lastGpsUpdate: '1 min ago',
    status: 'MOVING',
    headingDeg: 260,
    currentWaypointIndex: 1,
  },
  {
    id: 'TRK-MZ-3109',
    vehicleNumber: 'MZ-01-K-3109 (Tata 1512 LPT)',
    driverName: 'Subrata Debnath',
    driverPhone: '+91 94361 70293',
    assignedShipmentId: 'MED-3391',
    commodity: 'Pediatric Vaccines',
    lat: 24.3200,
    lng: 92.2100, // Crossing Kumarghat
    speedKmh: 52,
    routeId: 'ROUTE-NH-208',
    routeName: 'NH-208 (Silchar - Kumarghat - Agartala)',
    eta: '5h 40m',
    riskLevel: 'LOW',
    lastGpsUpdate: '4 mins ago',
    status: 'MOVING',
    headingDeg: 215,
    currentWaypointIndex: 1,
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-101',
    type: 'LANDSLIDE',
    title: 'Severe Rockfall & Debris Flow at 29th Mile (Teesta Bazaar)',
    location: 'Teesta Canyon, Kalimpong / Sikkim Border',
    chainage: 'KM 29+400',
    gps: { lat: 26.9854, lng: 88.4891 },
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    reporter: 'Border Roads Organisation (Project Swastik, Unit 44)',
    timestamp: '11:38 IST',
    description: 'Catastrophic rockfall triggered by torrential 120mm rainfall. Entire two-lane carriageway buried under 1,400m³ of shale and basalt rock.',
    evidenceIds: ['EVD-301', 'EVD-302'],
    riskScore: 96,
    verificationStatus: 'VERIFIED',
    severity: 'CRITICAL',
  },
  {
    id: 'INC-102',
    type: 'FLOOD',
    title: 'Brahmaputra River Surge Crest Overflow at Tezpur Pier',
    location: 'Bhomoraguri Bridge Low Approach',
    chainage: 'KM 42+100',
    gps: { lat: 26.6120, lng: 92.8340 },
    routeId: 'ROUTE-NH-27',
    routeName: 'NH-27 (Guwahati - Nagaon - Tezpur)',
    reporter: 'Central Water Commission (CWC Sensor Node 09)',
    timestamp: '11:15 IST',
    description: 'Water level +1.8m above statutory danger mark. Heavy freight speeds capped at 20 km/h with continuous hydrodynamic scour monitoring.',
    evidenceIds: ['EVD-303'],
    riskScore: 68,
    verificationStatus: 'VERIFIED',
    severity: 'HIGH',
  },
  {
    id: 'INC-103',
    type: 'ROAD DAMAGE',
    title: 'Viscous Silt Accumulation & Mud Slip at Jowai Pass',
    location: 'Jowai Plateau East Bend',
    chainage: 'KM 118+400',
    gps: { lat: 25.3940, lng: 92.2810 },
    routeId: 'ROUTE-NH-6',
    routeName: 'NH-6 (Shillong - Jowai - Silchar)',
    reporter: 'Meghalaya PWD Field Office',
    timestamp: '11:02 IST',
    description: '400m stretch of highway covered in thick clay sludge causing severe wheel-spin and lane bottlenecks for heavy container freight.',
    evidenceIds: ['EVD-304'],
    riskScore: 52,
    verificationStatus: 'VERIFIED',
    severity: 'CAUTION',
  },
  {
    id: 'INC-104',
    type: 'ROAD DAMAGE',
    title: 'Shoulder Crevice & Geological Subsidence on Ridge',
    location: 'Kohima Bypass Outer Ridge',
    chainage: 'KM 64+100',
    gps: { lat: 25.7100, lng: 94.0450 },
    routeId: 'ROUTE-NH-29',
    routeName: 'NH-29 (Dimapur - Kohima Bypass)',
    reporter: 'Geological Survey of India (GSI NER Team)',
    timestamp: '10:45 IST',
    description: '12cm asphalt fissure identified along outer shoulder. Single-lane convoy operation with spotter flag-marshals.',
    evidenceIds: ['EVD-305'],
    riskScore: 74,
    verificationStatus: 'VERIFIED',
    severity: 'HIGH',
  },
  {
    id: 'INC-105',
    type: 'HEAVY RAIN',
    title: 'Torrential Cloudburst Hazard & Low Visibility',
    location: 'Sela Tunnel South Approach',
    chainage: 'KM 188+000',
    gps: { lat: 27.4820, lng: 92.1290 },
    routeId: 'ROUTE-NH-13',
    routeName: 'NH-13 (Bhalukpong - Bomdila - Tawang)',
    reporter: 'ITBP High Altitude Patrol 03',
    timestamp: '10:20 IST',
    description: 'Visibility collapsed below 15 meters in heavy mist and sleet. Convoys restricted to guided formation.',
    evidenceIds: ['EVD-306'],
    riskScore: 65,
    verificationStatus: 'VERIFIED',
    severity: 'HIGH',
  },
  {
    id: 'INC-106',
    type: 'FLOOD',
    title: 'Wildlife Crossing Corridor Surface Waterlogging',
    location: 'Kaziranga Buffer Zone Segment 3',
    chainage: 'KM 78+200',
    gps: { lat: 26.5810, lng: 93.1890 },
    routeId: 'ROUTE-NH-715',
    routeName: 'NH-715 (Jorhat - Kaziranga - Kaliabor)',
    reporter: 'Assam Forest Department Dispatch',
    timestamp: '09:55 IST',
    description: 'Backwater overflow from Difolu river onto low shoulder. Speed radar enforcement active at 40 km/h.',
    evidenceIds: ['EVD-307'],
    riskScore: 48,
    verificationStatus: 'VERIFIED',
    severity: 'CAUTION',
  },
  {
    id: 'INC-107',
    type: 'BRIDGE DAMAGE',
    title: 'Scour Erosion on Pier 4 Abutment',
    location: 'Teesta Barrage Canal Bridge',
    chainage: 'KM 12+800',
    gps: { lat: 26.7820, lng: 88.4210 },
    routeId: 'ROUTE-NH-10',
    routeName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    reporter: 'West Bengal Irrigation & Waterways Directorate',
    timestamp: '09:30 IST',
    description: 'High velocity discharge causing foundation scouring. Geotechnical divers conducting structural sonic testing.',
    evidenceIds: ['EVD-308'],
    riskScore: 42,
    verificationStatus: 'PENDING',
    severity: 'CAUTION',
  },
  {
    id: 'INC-108',
    type: 'TRAFFIC',
    title: 'Stranded Multi-Axle Overturned Trailer Bottleneck',
    location: 'Nongstoin Junction Bypass',
    chainage: 'KM 54+300',
    gps: { lat: 25.5200, lng: 91.2600 },
    routeId: 'ROUTE-NH-6',
    routeName: 'NH-6 (Shillong - Jowai - Silchar)',
    reporter: 'Meghalaya Highway Traffic Police',
    timestamp: '09:12 IST',
    description: 'Overturned commercial cement carrier partially blocking northbound lane. Recovery hydraulic crane on site.',
    evidenceIds: ['EVD-309'],
    riskScore: 38,
    verificationStatus: 'VERIFIED',
    severity: 'CAUTION',
  },
  {
    id: 'INC-109',
    type: 'ACCIDENT',
    title: 'Fuel Tanker Skid near Chumukedima Gate',
    location: 'Chumukedima Hairpin 04',
    chainage: 'KM 18+200',
    gps: { lat: 25.8100, lng: 93.8400 },
    routeId: 'ROUTE-NH-29',
    routeName: 'NH-29 (Dimapur - Kohima Bypass)',
    reporter: 'Nagaland State Disaster Management Authority',
    timestamp: '08:45 IST',
    description: 'Minor diesel slick treated with dry absorbent sand. Normal transit resuming shortly.',
    evidenceIds: ['EVD-310'],
    riskScore: 35,
    verificationStatus: 'REJECTED',
    severity: 'INFO',
  },
  {
    id: 'INC-110',
    type: 'BLOCKED ROAD',
    title: 'Boulder Obstruction on Upper Hairpin',
    location: 'Dirang-Bomdila Pass',
    chainage: 'KM 142+100',
    gps: { lat: 27.3100, lng: 92.3500 },
    routeId: 'ROUTE-NH-13',
    routeName: 'NH-13 (Bhalukpong - Bomdila - Tawang)',
    reporter: 'BRO Task Force Vartak',
    timestamp: '08:20 IST',
    description: 'Isolated 8-tonne boulder shifted onto road shoulder. Blast fragmentation team en route.',
    evidenceIds: ['EVD-306'],
    riskScore: 58,
    verificationStatus: 'PENDING',
    severity: 'HIGH',
  },
];

export const INITIAL_EVIDENCE: EvidenceItem[] = [
  {
    id: 'EVD-301',
    incidentId: 'INC-101',
    incidentTitle: 'Severe Rockfall at 29th Mile (Teesta Bazaar)',
    routeId: 'ROUTE-NH-10',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDSMlf0C2R91Rs5pNzALBGCkzezif4h5GXdQi8rLOJW4epmMDMTNQ4JnMpgPh4v1_vwng-sKPcQhwxqqGDEL16E2P_S4o7woNNXPR7nE73dqR2nJexXi2cCq-vJJCdGxMH8sTEZQG8w9C6VceNiwhIoxoDZ2Mknb_l814QlKm1Y9fN6GsVyXJH5nCqI-_nDt3vUGxxW1RjFZmlpBwjcD0zlTTIlpIO95HSeFFlYAKCeTIrfh2i6O4czSA',
    gps: { lat: 26.9854, lng: 88.4891 },
    locationName: 'KM 29+400 Aerial PWD Drone',
    timestamp: '11:38 IST',
    reporter: 'PWD Drone Surveillance Wing',
    description: 'High altitude drone aerial photograph showing massive wet shale and mud landslide completely covering mountain highway.',
    aiDetectionLabel: 'YOLO: ROCKFALL 98.4%',
    aiConfidencePct: 98,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-302',
    incidentId: 'INC-101',
    incidentTitle: 'Severe Rockfall at 29th Mile (Teesta Bazaar)',
    routeId: 'ROUTE-NH-10',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDolPRVin6WlECI3vD-mKhZSvDVjPUTQ3tVJGEt_mRNK7iEfs2hvaHhVNXMXxjIUFN9t2UqRGgbYu7H_K4tyTnOP-IqzycQnPCIPs3JZMQ80dN2rakoHN9U1qM79YheEXuAER1benb3H9ed_btt291u4d20euxfoDq-DHaJOo-UzVRbFoTAHuxABAc61DUsbMpOKBWq7DXnJRMMLjc977rC5HBwy8giI55Jp0-WovkNOAJxH1HqysktMQ',
    gps: { lat: 26.9850, lng: 88.4885 },
    locationName: 'BRO Inspector Cam #11',
    timestamp: '11:40 IST',
    reporter: 'BRO Project Swastik Officer',
    description: 'Ground team tactical photo of broken guard rails and mud debris obstruction blocking carriageway.',
    aiDetectionLabel: 'BREACH: 42M CARRIAGEWAY 94.2%',
    aiConfidencePct: 94,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-303',
    incidentId: 'INC-102',
    incidentTitle: 'Brahmaputra Crest Overflow near Tezpur',
    routeId: 'ROUTE-NH-27',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYjzd9uW7haFVTlziW1ByujxsJ5_uZ_5lNHdv78xn5TBA1D0cQxoklfVEmi8LT6tc3mJr4wIgyyyKzjYYG1vZUITyF2-sFceO_GfFk2Oed7VTnGbP1zuhFR4bM-1z6WY_ItvPrfnZG1fjXQEADhnLFczREUOBL9cI1-n80cPEA9oeuvo3JESarZyr5SVCAnoxRxQxk3ZN8f6bKfSuIIqdBwtPtQ-uXjAQBQzSkLmTPFl1UiLPkKPECoQ',
    gps: { lat: 26.6120, lng: 92.8340 },
    locationName: 'Tezpur Low Pier Water Gauge',
    timestamp: '11:15 IST',
    reporter: 'CWC Remote Hydrocam',
    description: 'Turbulent muddy river floodwater overflowing onto low bridge highway approach.',
    aiDetectionLabel: 'CNN: FLOOD_SUBMERGENCE 91.5%',
    aiConfidencePct: 92,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-304',
    incidentId: 'INC-103',
    incidentTitle: 'Viscous Silt & Mud Slip at Jowai Pass',
    routeId: 'ROUTE-NH-6',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCb38KNMTaIClUHVE46oswFDt9nC6fjguc_7iwgubXgVm_hBwi3u6c78cszHbxv55g8YgdYl3M8UiJ_YaZ6xOZzCwzLkGzmRmCjS5F6mtaBncDigd83J_cImL5fBwsNenayl1UQjBp18GmpPXKG65RTUvnbkPGQtSTEUpqeDODtLbyNXjxIlchDR3O1CSpUzUmwc5KujBc4JgK_djFaeGV7Qo_PJElgUTitZeQAXI2O_0-lqIoaymq6QA',
    gps: { lat: 25.3940, lng: 92.2810 },
    locationName: 'KM 118+400 Meghalaya PWD CCTV',
    timestamp: '11:02 IST',
    reporter: 'Meghalaya PWD Field Station',
    description: 'Heavy mud slip on mountain bend road in misty rainforest with freight truck tires slipping.',
    aiDetectionLabel: 'YOLO: TRACTION_HAZARD 88.7%',
    aiConfidencePct: 89,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-305',
    incidentId: 'INC-104',
    incidentTitle: 'Shoulder Crevice & Subsidence on Ridge',
    routeId: 'ROUTE-NH-29',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMtDyCiOxSyq5hj6EdnPFTOJD0NVHWRlSQ80PlAmbZtDgjxUbshD6yDxVZQQPSfTZ02WJBmLBYMEdqaBDciMSZw7pqYtP72oox5DUJWHY7ebXryB-HNDDO94_0LODxk2VxH8_ynuL7OyrpvEJvCGEFXKTN5GzhplzRHEZS7vJFkzVAdlW21QMRW010mTj5Y-R4m_m8hKhySoFnGO3ov4DpUXUhZPLNjjtofElAhhlPGJqA7umC_sjDeg',
    gps: { lat: 25.7100, lng: 94.0450 },
    locationName: 'KM 64+100 Geotechnical Marker',
    timestamp: '10:45 IST',
    reporter: 'GSI Field Scientist',
    description: 'Roadway asphalt cracking and subsidence on steep ridge highway with monitoring stakes.',
    aiDetectionLabel: 'CNN: FISSURE_DETECTED 93.1%',
    aiConfidencePct: 93,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-306',
    incidentId: 'INC-105',
    incidentTitle: 'Torrential Cloudburst Hazard & Sleet',
    routeId: 'ROUTE-NH-13',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUy-ca28jtXtNNd4eu-vkG15iuvYDdbXjtEmr5S99hcKipVcE82nTOppyD26a8LHf0POIzx-h3SHhZmPvKimdL-RX17XFC3ReLfpHKUZXk2wetqNbKuEcZOyiN-tv89mKHTyHRFDQbT2CHojskbfKxDG5x44OOP6A4KJNWZPgM-G16eCCDPZltWi_jDX991JX9csGfuQ_QSb7rYk8fq04A9NaQt6eRveRJbI3hVwEhmvJAxllY4p6DWA',
    gps: { lat: 27.4820, lng: 92.1290 },
    locationName: 'Sela Pass South Webcam',
    timestamp: '10:20 IST',
    reporter: 'ITBP High Altitude Surveillance',
    description: 'Dense fog and boulder debris accumulation on high mountain pass.',
    aiDetectionLabel: 'YOLO: VISIBILITY_DEGRADED 86.4%',
    aiConfidencePct: 86,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-307',
    incidentId: 'INC-106',
    incidentTitle: 'Wildlife Corridor Surface Waterlogging',
    routeId: 'ROUTE-NH-715',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYjzd9uW7haFVTlziW1ByujxsJ5_uZ_5lNHdv78xn5TBA1D0cQxoklfVEmi8LT6tc3mJr4wIgyyyKzjYYG1vZUITyF2-sFceO_GfFk2Oed7VTnGbP1zuhFR4bM-1z6WY_ItvPrfnZG1fjXQEADhnLFczREUOBL9cI1-n80cPEA9oeuvo3JESarZyr5SVCAnoxRxQxk3ZN8f6bKfSuIIqdBwtPtQ-uXjAQBQzSkLmTPFl1UiLPkKPECoQ',
    gps: { lat: 26.5810, lng: 93.1890 },
    locationName: 'KM 78+200 Forest Patrol Cam',
    timestamp: '09:55 IST',
    reporter: 'Assam Forest Ranger',
    description: 'Shallow standing water on outer shoulder near Kaziranga animal transit underpass.',
    aiDetectionLabel: 'CNN: WATERLOG_SURFACE 82.0%',
    aiConfidencePct: 82,
    verificationStatus: 'PENDING',
  },
  {
    id: 'EVD-308',
    incidentId: 'INC-107',
    incidentTitle: 'Scour Erosion on Pier 4 Abutment',
    routeId: 'ROUTE-NH-10',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDolPRVin6WlECI3vD-mKhZSvDVjPUTQ3tVJGEt_mRNK7iEfs2hvaHhVNXMXxjIUFN9t2UqRGgbYu7H_K4tyTnOP-IqzycQnPCIPs3JZMQ80dN2rakoHN9U1qM79YheEXuAER1benb3H9ed_btt291u4d20euxfoDq-DHaJOo-UzVRbFoTAHuxABAc61DUsbMpOKBWq7DXnJRMMLjc977rC5HBwy8giI55Jp0-WovkNOAJxH1HqysktMQ',
    gps: { lat: 26.7820, lng: 88.4210 },
    locationName: 'Teesta Barrage Sensor Station',
    timestamp: '09:30 IST',
    reporter: 'Irrigation Field Inspector',
    description: 'High velocity river current eroding embankment toe near bridge abutment.',
    aiDetectionLabel: 'CNN: EROSION_RISK 79.4%',
    aiConfidencePct: 79,
    verificationStatus: 'PENDING',
  },
  {
    id: 'EVD-309',
    incidentId: 'INC-108',
    incidentTitle: 'Stranded Multi-Axle Overturned Trailer',
    routeId: 'ROUTE-NH-6',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCb38KNMTaIClUHVE46oswFDt9nC6fjguc_7iwgubXgVm_hBwi3u6c78cszHbxv55g8YgdYl3M8UiJ_YaZ6xOZzCwzLkGzmRmCjS5F6mtaBncDigd83J_cImL5fBwsNenayl1UQjBp18GmpPXKG65RTUvnbkPGQtSTEUpqeDODtLbyNXjxIlchDR3O1CSpUzUmwc5KujBc4JgK_djFaeGV7Qo_PJElgUTitZeQAXI2O_0-lqIoaymq6QA',
    gps: { lat: 25.5200, lng: 91.2600 },
    locationName: 'Nongstoin Traffic Cam',
    timestamp: '09:12 IST',
    reporter: 'Highway Police Patrol',
    description: 'Overturned carrier blocking northbound transit lane.',
    aiDetectionLabel: 'YOLO: VEHICLE_INCIDENT 95.0%',
    aiConfidencePct: 95,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'EVD-310',
    incidentId: 'INC-109',
    incidentTitle: 'Fuel Tanker Skid near Chumukedima Gate',
    routeId: 'ROUTE-NH-29',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMtDyCiOxSyq5hj6EdnPFTOJD0NVHWRlSQ80PlAmbZtDgjxUbshD6yDxVZQQPSfTZ02WJBmLBYMEdqaBDciMSZw7pqYtP72oox5DUJWHY7ebXryB-HNDDO94_0LODxk2VxH8_ynuL7OyrpvEJvCGEFXKTN5GzhplzRHEZS7vJFkzVAdlW21QMRW010mTj5Y-R4m_m8hKhySoFnGO3ov4DpUXUhZPLNjjtofElAhhlPGJqA7umC_sjDeg',
    gps: { lat: 25.8100, lng: 93.8400 },
    locationName: 'Chumukedima Toll Cam',
    timestamp: '08:45 IST',
    reporter: 'Toll Operator Desk',
    description: 'Minor diesel slick treated with sand, no blockage remaining.',
    aiDetectionLabel: 'CNN: SLICK_TREATED 81.2%',
    aiConfidencePct: 81,
    verificationStatus: 'REJECTED',
  },
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'ALT-501',
    type: 'ROAD BLOCKED',
    severity: 'CRITICAL',
    title: 'NH-10 Sevoke - Gangtok: Blocked at Mile 29',
    location: 'Teesta Canyon (KM 29+400)',
    timestamp: '11:38 IST',
    cause: 'Major mud-rock cascade triggered by 120mm rainfall. 3 high-priority transports stalled.',
    affectedRouteId: 'ROUTE-NH-10',
    affectedRouteName: 'NH-10 (Siliguri - Sevoke - Gangtok)',
    affectedShipmentId: 'MED-2045',
    recommendedAction: 'Execute emergency AI reroute for Convoy TRK-AS-1029 via Lava-Algarah Corridor Alt-B.',
    isAcknowledged: false,
  },
  {
    id: 'ALT-502',
    type: 'FLOOD RISK',
    severity: 'HIGH',
    title: 'Brahmaputra Crest Overflow Near Tezpur Pier Approach',
    location: 'Bhomoraguri Crossing (KM 42+100)',
    timestamp: '11:15 IST',
    cause: 'Water level +1.8m above danger mark near bridge approach. Heavy transport speeds restricted.',
    affectedRouteId: 'ROUTE-NH-27',
    affectedRouteName: 'NH-27 (Guwahati - Nagaon - Tezpur)',
    affectedShipmentId: 'OXY-902',
    recommendedAction: 'Notify convoy control to cap speeds at 20 km/h and deploy hydro-scour watch.',
    isAcknowledged: false,
  },
  {
    id: 'ALT-503',
    type: 'ROAD DAMAGE',
    severity: 'CAUTION',
    title: 'NH-6 Jowai-Ratacherra Heavy Siltation & Mud Drag',
    location: 'Jowai Pass (KM 118+400)',
    timestamp: '11:02 IST',
    cause: 'Continuous showers causing wheel-drag on multi-axle freight. SDRF clearance operating.',
    affectedRouteId: 'ROUTE-NH-6',
    affectedRouteName: 'NH-6 (Shillong - Jowai - Silchar)',
    affectedShipmentId: 'RAT-3012',
    recommendedAction: 'Dispatch pilot escort and monitor tire traction on Meghalaya incline.',
    isAcknowledged: false,
  },
  {
    id: 'ALT-504',
    type: 'HIGH-RISK ROUTE',
    severity: 'HIGH',
    title: 'NH-29 Kohima Ridge Roadway Crevice Advisory',
    location: 'Kohima Bypass (KM 64+100)',
    timestamp: '10:45 IST',
    cause: '12cm asphalt fissure identified along outer shoulder. Single-lane convoy operation.',
    affectedRouteId: 'ROUTE-NH-29',
    affectedRouteName: 'NH-29 (Dimapur - Kohima Bypass)',
    affectedShipmentId: 'DIS-9901',
    recommendedAction: 'Hold multi-axles over 20 tonnes at Chumukedima staging area.',
    isAcknowledged: false,
  },
];

export const INITIAL_AUDIT_TRAIL: AuditEvent[] = [
  {
    id: 'AUD-001',
    timestamp: '09:30:12 IST',
    action: 'System Initialized',
    user: 'Rajeev Sharma (Authority)',
    entity: 'EXTRICATE Core Engine',
    previousState: 'OFFLINE',
    newState: 'SYS OPERATIONAL',
    details: 'Loaded North Eastern Region (NER) Sector 4 tactical grid and 10 registered corridors.',
  },
  {
    id: 'AUD-002',
    timestamp: '10:15:44 IST',
    action: 'Shipment Scheduled',
    user: 'Rajeev Sharma (Authority)',
    entity: 'Shipment MED-2045',
    previousState: 'PLANNED',
    newState: 'IN TRANSIT',
    details: 'Dispatched 4.8T Hemodialysis Units on vehicle TRK-AS-1029 via NH-10.',
  },
  {
    id: 'AUD-003',
    timestamp: '10:45:18 IST',
    action: 'Geological Alert Logged',
    user: 'GSI Field Scientist',
    entity: 'Route NH-29',
    previousState: 'OPEN',
    newState: 'HIGH-RISK',
    details: '12cm shoulder fissure detected at KM 64+100, risk score upgraded to 74.',
  },
  {
    id: 'AUD-004',
    timestamp: '11:02:05 IST',
    action: 'Route Condition Updated',
    user: 'Meghalaya PWD',
    entity: 'Route NH-6',
    previousState: 'OPEN',
    newState: 'DEGRADED',
    details: 'Silt accumulation reported at Jowai Pass, +45m delay added.',
  },
  {
    id: 'AUD-005',
    timestamp: '11:38:22 IST',
    action: 'Field Evidence Uploaded',
    user: 'BRO Project Swastik Officer',
    entity: 'Evidence EVD-301',
    previousState: 'PENDING',
    newState: 'VERIFIED',
    details: 'High altitude drone aerial photo verified rockfall breach at KM 29+400.',
  },
];
